project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
 
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
          - text: In-class Exercise 2
          - text: In-class Exercise 3
            href: In-class_Ex/In-class_Ex3/In-class_Ex3.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

